#ifndef CONFIG_H
#define CONFIG_H
#include <EEPROM.h>
#include <Servo.h>


#define RELEASE "v.1.0" 

#define MODE_CONTROL "NORMAL" 
#define MODE_RECORD "RECORD" 
#define MODE_REPEAT "REPEAT" 
#define MODE_USB "USB" 
#define MODE_RADIO "RADIO" 
#define MODE_BLUETOOTH "BLUETOOTH" 
#define MODE_WIFI "WIFI" 
#define DEFAULT_SCREEN 0
#define EEPROM_ADDR_TH 11
#define EEPROM_ADDR_YA 22
#define EEPROM_ADDR_RO 33
#define EEPROM_ADDR_PI 44
#define EEPROM_ADDR_WRITE_NB 55
#define TITLE_PEDRO "PEDRO" 
#define TITLE_MODE "SELECT MODE" 
#define TITLE_RADIO "RADIO" 
#define TITLE_DLE "PEDRO ROBOT" 
#define SCREEN_NORMAL 1
#define SCREEN_SETTINGS 2
#define SCREEN_RADIO 3
#define TYPE_TX "TRANSMITTER" 
#define TYPE_RX "RECEIVER" 

#define LEVELWIDTH 17
#define LEVELWIDTH_ 13
#define SCREEN_SIZE_X 128
#define SCREEN_SIZE_Y 64
// PIN BUTTON
#define BTNLEFT   A2
#define BTNCENTER A0
#define BTNRIGHT  A1

#define DEBOUNCE_DELAY 5

#endif // CONFIGURATION_H


